title: Ungarala Naga Venkata Sai Pradeep
description: DevOps Engineer specializing in CI/CD, IaC, and Cloud Infrastructure.
theme: jekyll-theme-architect # This provides a clean, modern developer layout

# Personalization
email: pradeepungarala2000@example.com
linkedin_username: www.linkedin.com/in/pradeep-ungarala
github_username: https://github.com/Pradeep-219
